pipeline {
  agent any

  environment {
    IMAGE_NAME = "jrodga1604/sparta-app"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Push Docker Image (amd64)') {
      steps {
        dir('app') {
          sh """
            docker buildx create --use --name multi-builder || true
            docker buildx build \
              --platform linux/amd64 \
              -t $IMAGE_NAME:$BUILD_NUMBER \
              -t $IMAGE_NAME:latest \
              --push .
          """
        }
      }
    }

  }
}
